
create table faculty
(
    id    bigint generated by default as identity
        primary key,
    color varchar(255),
    name  varchar(255),
    constraint name_color_unique
        unique (name, color)
)

