create table student
(
    id         bigint generated by default as identity
        primary key,
    age        integer default 20
        constraint age_constraint
            check (age > 15),
    name       varchar(255) not null
        constraint name_unique
            unique,
    faculty_id bigint
        constraint fac_id
            references faculty
)

GO