create table avatar
(
    id         bigint generated by default as identity
        primary key,
    data       oid,
    file_path  varchar(255),
    media_type varchar(255),
    student_id bigint
        constraint st_id
            references student(id),
    file_size  bigint not null
)

GO