-- liquibase formatted sql

create table faculty
(
    id    bigint generated by default as identity
        primary key,
    name  varchar(255),
    color varchar(255)
    constraint name_color unique (name, color)
);